server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  cloud:
    gateway:
      mvc:
        routes:

          # ------------------------------
          # MICROSERVICE ELECTRIC SCOOTER
          # ------------------------------
          - id: microservice-electric_scooter
            uri: lb://microservice-electric_scooter
            predicates:
              - Path=/api/scooters/**

          # ------------------------------
          # MICROSERVICE PAYMENT
          # ------------------------------
          - id: microservice-payment
            uri: lb://microservice-payment
            predicates:
              - Path=/api/rates/**

          # ------------------------------
          # MICROSERVICE STOP
          # ------------------------------
          - id: microservice-stop
            uri: lb://microservice-stop
            predicates:
              - Path=/api/stops/**

          # ------------------------------
          # MICROSERVICE TRAVEL
          # ------------------------------
          - id: microservice-travel
            uri: lb://microservice-travel
            predicates:
              - Path=/api/travels/**

          # ------------------------------
          # MICROSERVICE USER
          # ------------------------------
          # API de cuentas
          - id: microservice-user-accounts
            uri: lb://microservice-user
            predicates:
              - Path=/api/accounts/**

          # API de usuarios
          - id: microservice-user-users
            uri: lb://microservice-user
            predicates:
              - Path=/api/users/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG