server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3312/auth?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      mvc:
        routes:

          # ------------------------------
          # MICROSERVICE ELECTRIC SCOOTER
          # ------------------------------
          - id: microservice-electric_scooter
            uri: http://localhost:8082
            predicates:
              - Path=/api/scooters/**

          # ------------------------------
          # MICROSERVICE PAYMENT
          # ------------------------------
          - id: microservice-payment
            uri: http://localhost:8083
            predicates:
              - Path=/api/rates/**

          # ------------------------------
          # MICROSERVICE STOP
          # ------------------------------
          - id: microservice-stop
            uri: http://localhost:8081
            predicates:
              - Path=/api/stops/**

          # ------------------------------
          # MICROSERVICE TRAVEL
          # ------------------------------
          - id: microservice-travel
            uri: http://localhost:8084
            predicates:
              - Path=/api/travels/**

          # ------------------------------
          # MICROSERVICE USER
          # ------------------------------
          # API de cuentas
          - id: microservice-user-accounts
            uri: http://localhost:8085
            predicates:
              - Path=/api/accounts/**

          # API de usuarios
          - id: microservice-user-users
            uri: http://localhost:8085
            predicates:
              - Path=/api/users/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG